export enum ListActionTypes {
  ADD_NEW_LIST = 'ADD_NEW_LIST',
  UPDATE_LIST = 'UPDATE_LIST',
  REMOVE_LIST = 'REMOVE_LIST',
  REMOVE_ITEM_FROM_LIST = 'REMOVE_ITEM_FROM_LIST',
  FETCH_LISTS = 'FETCH_LISTS',
  GET_LIST = 'GET_LIST',
  UPDATE_ALL_LISTS = 'UPDATE_ALL_LISTS',
  CHOOSE_ITEM = 'CHOOSE_ITEM',
  ACCEPT_INVITE = 'ACCEPT_INVITE',
}
